### ISSUE TITLE
Value calculation fails

### ISSUE THREAD

**Issue by monstermichl** [monstermichl/confluent#3]
Combination of float/double/int values does not work. For example
````yaml
- type: float
  name: FACTOR
  value: 0.44

- type: float
  name: VALUE
  value: 100

- type: float
  name: REDUCED_VALUE
  value: ${VALUE} * ${FACTOR}
````

results in

````Java
// Generated with confluent v0.1.0 (https://pypi.org/project/confluent/).
public class TestConfig {
    public final static float FACTOR = 0.44f;
    public final static float VALUE = 100f;
    public final static float REDUCED_VALUE = 0f;
}
````
