### ISSUE TITLE
Hyphen in inclusion alias causes problems

### ISSUE THREAD

**Issue by monstermichl** [monstermichl/confluent#8]
If the configuration inclusion alias contains a hyphen, substitution doesn't work anymore. E.g.,
```yaml
includes:
  - path: generic-regex-config.yaml
    as: generic-regex
```
